### ISSUE TITLE
Solution file reference to Test.csproj broken on linux

### ISSUE THREAD

**Issue by ttutko** [dj-nitehawk/MongoWebApiStarter#1]
The solution file reference looks like:
`Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Test", "Test\Test.csproj", "{2BD73B73-BE97-41AC-BA56-48E8D873DCE9}"
EndProject`

With a capital "T" for the sub folder "Test" but really the csproj exists at "test\Test.csproj". This causes the solution to fail to build/load on linux.

**Comment by dj-nitehawk** [comment]
oops.... fixed... thanks for reporting :-)
