### ISSUE TITLE
how do I use this from a mac

### ISSUE THREAD

**Issue by FELS-Zak** [dj-nitehawk/MongoWebApiStarter#2]
Hi - 
I cloned this to the mac, now what ? how to do I run it ?

**Comment by dj-nitehawk** [comment]
you don't need to clone the repo.
just scaffold a new project using `dotnet new` cli command after [installing the .net core sdk on your mac](https://docs.microsoft.com/en-us/dotnet/core/install/macos).

```
  dotnet new -i MongoWebApiStarter
  dotnet new mongowebapi -n MyAwesomeApp
```

**Comment by FELS-Zak** [comment]
got it. But I can't see how to run the api 
I got the starter project when I run it, it loads on local :8888 
What's the api  - ?? is there a swagger ? 

regards

**Comment by dj-nitehawk** [comment]
if you're not familiar with servicestack please check the docs here: https://docs.servicestack.net/
this explains how to add swagger: https://docs.servicestack.net/swagger-api
you can see the [endpoint urls](https://github.com/dj-nitehawk/MongoWebApiStarter/blob/44c381dcef163754cd5a5b5f45abe3014bc7021a/Template/Source/%5BFeatures%5D/Account/Save/Request.cs#L8) on each request dto of every feature together with what fields are needed for the request.
also look at the tests to see how it's being used: https://github.com/dj-nitehawk/MongoWebApiStarter/blob/master/Template/Tests/Main/Account.cs
i'll add a postman export file to the project soon...

**Comment by FELS-Zak** [comment]
Can I use this with asp standard apiController?

**Comment by dj-nitehawk** [comment]
ummm... no, this doesn't use asp.net mvc/web-api controllers. it uses servicestack services instead.
but you can easily see how this works and implement the same/similar vertical feature architecture with asp.net controllers too i suppose. i just find servicestack far superior and gave up on asp/mvc sometime back.

**update:** added [postman export](https://github.com/dj-nitehawk/MongoWebApiStarter/blob/master/Template/Source/%5BFeatures%5D/API-Reference-Postman-Export.json)
