### ISSUE TITLE
Failed to run command "dotnet new mongowebapi -n sss".

### ISSUE THREAD

**Issue by chen-pseudonym** [dj-nitehawk/MongoWebApiStarter#5]
With the latest commit, it fails to run command "dotnet new mongowebapi -n sss".
The error message is:
**Unable create template.**
**Details: Sequence contains no matching element。**
**For more information, please reference https://aka.ms/templating-exit-codes#100**

**Comment by dj-nitehawk** [comment]
apparantly it's a bug in .net 7
works fine with .net 6
however, i've done a workaround in `v7.8.1` so it works now with .net 7 too.
