### ISSUE TITLE
How do I add User Secrets to Settings?

### ISSUE THREAD

**Issue by WeismanGitHub** [dj-nitehawk/MongoWebApiStarter#6]
Sorry if this is a stupid question. I'm new to C#.

In `appsettings.json` there's several empty strings for secrets, but shouldn't they be stored as User Secrets in `secrets.json`?

In `Program.cs`, this is the code for adding `Settings`.
```cs
var sec = bld.Configuration.GetSection(nameof(Settings));
var stn = sec.Get<Settings>()!;

bld.Services
   .Configure<Settings>(sec)
```
Then, in `/Features/Account/Login/Endpoint`, you access the settings with `public IOptions<Settings> Settings { get; set; } = null!;`.

But what if I want to I wanted to add `SigningKey` from `secrets.json` instead of `appsettings.json` to Settings?

**Comment by dj-nitehawk** [comment]
nothing special needs to be done to pickup the values from user secrets other than having the matching json structure in the user secrets file. see this walk-through: https://streamable.com/uureaf

if i remember correctly, the default priority of configuration settings goes like this:

1. environment variables > 2. user secrets > 3. appsettings.json

so in the example above, user secret set for `Settings.Auth.SigningKey` overrides the value set in `appsettings.json`.

hope that explains it.

here's the doc page for configuration if you wanna dig deeper: https://learn.microsoft.com/en-us/aspnet/core/fundamentals/configuration
